name: caller

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Comment
        id: pr-comment
        run: |
          echo ::set-output name=comment::$(echo $PR_COMMENT | cut -d "[" -f2 | cut -d "]" -f1)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}
      - name: Run if previous step outputs "@deploy otc" word
        if: contains(steps.pr-comment.outputs.comment, '@deploy otc')
        run: |
          echo ${{ steps.pr-comment.outputs.comment }}

  call-another-workflow: 
    if: contains(steps.pr-comment.outputs.comment, '@deploy otc')
    uses: atasen19/pm/.github/workflows/test.yml@main


