name: BURAYA BAK
on: 
  push:

env:
  # ECR Repositories
  ECR_MAIN_REPOSITORY: pandora-main/sandbox
  ECR_ORGANIZATIONS_REPOSITORY: pandora-organizations/sandbox
  ECR_OTC_REPOSITORY: pandora-otc/sandbox

# jobs:
#   loope_test:
#     # This job only runs for pull request comments
#     name: loop test
#     # if: ${{ github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: run loop
#         id: test-$x
#         env:
#           REPOSITORIES: ${{env.ECR_MAIN_REPOSITORY}} ${{env.ECR_ORGANIZATIONS_REPOSITORY}} ${{env.ECR_OTC_REPOSITORY}}
#         run: |
#           for x in $REPOSITORIES; do
#             echo "$x"
#           done

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - name: run loop
        run: |
          echo ${{matrix.version}} ${{matrix.os}}

