name: BURAYA BAK
on: 
  push:

env:
  # ECR Repositories
  ECR_MAIN_REPOSITORY: pandora-main/sandbox
  ECR_ORGANIZATIONS_REPOSITORY: pandora-organizations/sandbox
  ECR_OTC_REPOSITORY: pandora-otc/sandbox

jobs:
  loope_test:
    # This job only runs for pull request comments
    name: loop test
    # if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: run loop
        env:
          REPOSITORIES: ${{env.ECR_MAIN_REPOSITORY}}, A ${{env.ECR_ORGANIZATIONS_REPOSITORY}}, B ${{env.ECR_OTC_REPOSITORY}}, C
          DENEME: A B C
        run: |
          for x in $REPOSITORIES; do
            if [[$x == ${{env.ECR_MAIN_REPOSITORY}}]]; then
              echo A
            fi
            if [[$x == ${{env.ECR_ORGANIZATIONS_REPOSITORY}}]]; then
              echo B
            fi
            if [[$x == ${{env.ECR_OTC_REPOSITORY}}]]; then
              echo C
            fi
          done


