name: BURAYA BAK
on: 
  push:
 
env:
  # ECR Repositories
  ECR_MAIN_REPOSITORY: pandora-main/sandbox
  ECR_ORGANIZATIONS_REPOSITORY: pandora-organizations/sandbox
  ECR_OTC_REPOSITORY: pandora-otc/sandbox

jobs:
  loope_test:
    name: loop test
    strategy:
      matrix:
        machine_architecture: [32, 64]
    runs-on: ubuntu-latest
    steps:
      # - name: run loop
      #   env:
      #     REPOSITORIES: ${{env.ECR_MAIN_REPOSITORY}} ${{env.ECR_ORGANIZATIONS_REPOSITORY}} ${{env.ECR_OTC_REPOSITORY}}
      #     DENEME: A B C
      #   run: |
      #     for x in $REPOSITORIES; do
      #       if [ $x == pandora-main/sandbox ]; then
      #         echo A
      #       elif [ $x == pandora-organizations/sandbox ]; then
      #         echo B
      #       elif [ $x == pandora-otc/sandbox ]; then
      #         echo C
      #       fi
      #     done
      #   shell: bash

      - name: deneme
        run: |
          echo ${{ fromJson('{ 32: "i386", 64: "x86_64" }')[machine_architecture] }}
        shell: bash
        


