name: "PM"
on:
  issues:
    types:
      - opened
      - assigned

jobs:

  automate-project-columns:
    name: Automate STH
    runs-on: ubuntu-latest
    environment: PM
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.MY_PM_SECRET }}