name: Add PR to project
on:
  issues:
    types:
      - assigned
      - opened
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PM_SECRET }}
          ORGANIZATION: atasentech
          PROJECT_NUMBER: 2
        run: |
          gh api graphql -f query='
            query{
              organization(login: "ORGANIZATION"){
                projectV2(number: ${{ env.PROJECT_NUMBER }}) {
                  id
                }
              }
          }'
