name: Add PR to project
on:
  issues:
    types:
      - assigned
      - opened
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get Organization Project Data
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PM_SECRET }}
          PROJECT_NUMBER: 2
        run: |
          gh api graphql -f query='
            query{
              organization(login: "atasentech"){
                projectV2(number: ${{ env.PROJECT_NUMBER }}) {
                  id
                }
              }
          }'
      
      - name: Finding Information About Items in a Project
        env:
          GH_TOKEN: ${{ secrets.MY_PM_SECRET }}
        run: |
          gh api graphql -f query='
            query{
              node(id: "PVT_kwDOBvPcNM4AHpFn") {
                  ... on ProjectV2 {
                    items(first: 20) {
                      nodes{
                        id
                        fieldValues(first: 8) {
                          nodes{                
                            ... on ProjectV2ItemFieldTextValue {
                              text
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldDateValue {
                              date
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              name
                              field {
                                ... on ProjectV2FieldCommon {
                                  name
                                }
                              }
                            }
                          }              
                        }
                        content{              
                          ... on DraftIssue {
                            title
                            body
                          }
                          ... on Issue {
                            id
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                          ... on PullRequest {
                            title
                            assignees(first: 10) {
                              nodes{
                                login
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }'

      - name: Adding an Item (İSSUE) to a Project
        env:
          GH_TOKEN: ${{ secrets.MY_PM_SECRET }}
          PROJECT_ID: PVT_kwDOBvPcNM4AHpFn
          ISSUE_ID: PVTI_lADOBvPcNM4AHpFnzgDHwv4
        run: |
          gh api graphql -f query='
            mutation {
              addProjectV2ItemById(input: {projectId: "PVT_kwDOBvPcNM4AHpFn" contentId: "PVTI_lADOBvPcNM4AHpFnzgDHwv4" }) {
                item {
                  id
                }
              }
            }'