name: Add PR to project
on:
  issues:
    types:
      - assigned
      - opened
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
          ORGANIZATION: YOUR_ORGANIZATION
          PROJECT_NUMBER: YOUR_PROJECT_NUMBER
        run: |
          gh api graphql -f query='
            query{
              organization(login: "ORGANIZATION"){
                projectV2(number: NUMBER) {
                  id
                }
              }
          }'
