name: BURAYA BAK
on: 
  release:
    types: [published]

jobs:
  release_tag:
    # This job only runs for pull request comments
    name: Release Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.split.outputs.fragment }}
    steps:
      - name: Get Release Tag
        id: release-tag
        run: |
          echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d "[" -f2 | cut -d "]" -f1)
        env:
          GITHUB_REF: $GITHUB_REF

      - name: Split tag name
        env:
          TAG: ${{ steps.release-tag.outputs.tag }}
        id: split
        run: echo "::set-output name=fragment::${TAG#*-}"
      
      - name: Print
        run: echo ${{ steps.split.outputs.fragment}}

  deploy:
    needs: release_tag
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print Hey
        run: |
          echo ${{needs.release_tag.outputs.tag}}

