name: BURAYA BAK
on: 
  # workflow_dispatch:
  # workflow_call:
  # issue_comment:
  #   types: [created]
  #   branches:
  #     - new_deployment
  release:
    types: [published]

jobs:
  release_tag:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-tag.outputs.tag }}
    steps:
      - name: Get Release Tag
        id: release-tag
        run: |
          echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d "[" -f2 | cut -d "]" -f1)
        env:
          GITHUB_REF: $GITHUB_REF

      - name: Print Hey
        if: contains(steps.release-tag.outputs.tag, 'sandbox')
        run: |
          echo 'OLDU SANIRIM'

      - name: Split tag name
        env:
          TAG: ${{ steps.release-tag.outputs.tag }}
        id: split
        run: echo "::set-output name=fragment::${TAG##*-}"

      # - name: Get PR Comment
      #   id: pr-comment
      #   run: |
      #     echo ::set-output name=comment::$(echo $PR_COMMENT | cut -d "[" -f2 | cut -d "]" -f1)
      #   env:
      #     PR_COMMENT: ${{ github.event.comment.body }}
      # - name: Run if previous step outputs "@deploy otc" word
      #   if: contains(steps.pr-comment.outputs.comment, '@deploy otc')
      #   run: |
      #     echo ${{ steps.pr-comment.outputs.comment }}

  deploy:
    needs: release_tag
    if: contains(needs.release_tag.outputs.tag, 'sandbox')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print Hey
        # if: contains(steps.release-tag.outputs.tag, 'sandbox')
        run: |
          echo 'OLDU SANIRIM'
  # issue_commented:
  #   # This job only runs for issue comments
  #   name: Issue comment
  #   if: ${{ !github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on issue $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}
